# Generated by Django 3.0.4 on 2020-03-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('email', models.CharField(max_length=100, verbose_name='User email')),
                ('password', models.CharField(max_length=20, verbose_name='User password')),
            ],
        ),
    ]
