# Generated by Django 3.0.4 on 2020-03-14 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100, verbose_name='Post title')),
                ('description', models.TextField(verbose_name='Post Description')),
                ('posted_date', models.DateField(default=datetime.date.today)),
                ('good_name', models.CharField(max_length=100, verbose_name='Good name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentbook.User')),
            ],
        ),
    ]
